
#include <fstream>
#include <iomanip>
#include <sstream>

#include "../ParticleContainer.h"

/**
 * @brief Base class for all output writers. This can define the file
 * format as well as metadata.
 */
class Writer {
   protected:
    ParticleContainer &particles;

   public:
    /**
     * @note Default constructor without providing particle container is private.
     */
    Writer() = delete;

    /**
     * @brief Default constructor
     */
    Writer(ParticleContainer &p): particles(p) {}

    /**
     * @brief Destructor.
     */
    ~Writer() = default;

   protected:
    /**
     * @brief Standard file extension for this writer.
     */
    virtual const char* getExtension() const {
        return ".out";
    }

    /**
     * @brief Get file name for iteration.
     */
    std::string getFileName(const std::string &baseName, int iteration) const {
        std::stringstream strstr;
        strstr << baseName << "_" << std::setfill('0') << std::setw(4) << iteration << getExtension();
        return strstr.str();
    }

    /**
     * @brief Statically write before all particles.
     */
    const std::string writeMagicHeader() {
        std::stringstream strstr;
        strstr << "Generated by MolSim. Particles = " << particles.size() << "\n\n";
        return strstr.str();
    }

    /**
     * @brief Plot single particle.
     */
    const std::string plotSingleParticle(const Particle &part) {
        std::stringstream strstr;
        const Vec3D &pos = part.getPosition();
        strstr << pos.x << ", " << pos.y << ", " << pos.z << "\n";
        return strstr.str();
    }

   public:
    /**
     * @brief Plot particles to file, returns stream.
     */
    void plot(const std::string &filename, int iteration) {
        std::ofstream file;
        std::string full_filename = getFileName(filename, iteration);

        file.open(full_filename.c_str());
        file << writeMagicHeader();

        for (const auto &p : particles) {
            file << plotSingleParticle(p);
        }

        file.close();
    }
};
