
#pragma once

#include <fstream>
#include <iomanip>
#include <sstream>

#include "../ParticleContainer.h"

/**
 * @brief Base class for all output writers. This can define the file
 * format as well as metadata.
 */
class Writer {
   protected:
    ParticleContainer &particles;

   private:
    /**
     * @note Default constructor without providing particle container is private.
     */
    Writer() = delete;

   public:
    /**
     * @brief Default constructor
     */
    explicit Writer(ParticleContainer &p) : particles(p) {}

    // /**
    //  * @note Default constructor removed. The = operator however is explicitly
    //  * provided.
    //  */
    // Writer &operator=(const Writer &other) = default;
    // Writer &operator=(const Writer &other) {
    //     if (this == &other) {
    //         return *this;
    //     }

    //     this->particles = other.particles;
    //     return *this;
    // }

    /**
     * @brief Destructor.
     */
    ~Writer() = default;

    /**
     * @brief Standard file extension for this writer.
     */
    virtual const char *getExtension() const { return ".out"; }

   protected:
    /**
     * @brief Get file name for iteration.
     */
    virtual std::string getFileName(const std::string &baseName, int iteration) const {
        std::stringstream strstr;
        strstr << baseName << "_" << std::setfill('0') << std::setw(4) << iteration << getExtension();
        return strstr.str();
    }

    /**
     * @brief Statically write before all particles.
     */
    virtual const std::string writeMagicHeader() const {
        std::stringstream strstr;
        strstr << "Generated by MolSim. Particles = " << particles.size() << "\n\n";
        return strstr.str();
    }

    /**
     * @brief Plot single particle.
     */
    virtual const std::string plotSingleParticle(const Particle &part) const {
        std::stringstream strstr;
        const Vec3D &pos = part.getPosition();
        strstr << pos.x << ", " << pos.y << ", " << pos.z << "\n";
        return strstr.str();
    }

   public:
    /**
     * @brief Plot particles to file, returns stream.
     */
    virtual void plot(const std::string &filename, int iteration) const {
        std::ofstream file;
        std::string full_filename = getFileName(filename, iteration);

        file.open(full_filename.c_str());
        file << writeMagicHeader();

        for (const auto &p : particles) {
            file << plotSingleParticle(p);
        }

        file.close();
    }
};
