#pragma once

#include <fstream>
#include <list>

#include "Writer.h"
#include "../ParticleContainer.h"

namespace outputWriter {

class XYZWriter : public Writer {
   public:
    /**
     * @note Default constructor without providing particle container is private.
     */
    XYZWriter() = delete;

    /**
     * @brief Default constructor
     */
    XYZWriter(ParticleContainer &p): Writer(p) {}

    /**
     * @brief File Extension is '.xyz'
     * @override
     */
    const char* getExtension() const override {
        return ".xyz";
    }

    /**
     * @brief Statically write before all particles.
     */
   protected:
    const std::string writeMagicHeader() const {
        std::stringstream strstr;

        strstr << particles.size() << "\n";
        strstr << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
                   "file format documentation.\n";

        return strstr.str();
    }

    /**
     * @brief Plot single particle.
     */
    const std::string plotSingleParticle(const Particle &part) const {
        std::stringstream strstr;
        const Vec3D &pos = part.getPosition();

        strstr << "Ar ";
        strstr.setf(std::ios_base::showpoint);
        strstr << pos.x << " " << pos.y << " " << pos.z << " ";
        strstr << std::endl;

        return strstr.str();
    }
};

}
