/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "./XYZWriter.h"

#include <iomanip>
#include <sstream>

#include "../ParticleContainer.h"
#include "../math/Vec3.h"

namespace outputWriter {

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(ParticleContainer &particles, const std::string &filename, int iteration) {
    std::ofstream file;
    std::stringstream strstr;
    strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

    file.open(strstr.str().c_str());
    file << particles.size() << "\n";
    file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
            "file format doku.\n";

    for (const auto &p : particles) {
        const Vec3D &pos = p.getPosition();
        file << "Ar ";
        file.setf(std::ios_base::showpoint);
        file << pos.x << " " << pos.y << " " << pos.z << " \n";
    }

    file.close();
}

}  // namespace outputWriter
