/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <iostream>

#include "utils/ArrayUtils.h"
#include "math/Vec3.h"

Particle::Particle(int type_arg) {
  type = type_arg;
  std::cout << "Particle generated!" << std::endl;
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  std::cout << "Particle generated by copy!" << std::endl;
}

// Todo: maybe use initializater list instead of copy?
Particle::Particle(Vec3D x_arg, Vec3D v_arg, double m_arg, int type_arg) {
  x = x_arg;
  v = v_arg;
  m = m_arg;
  type = type_arg;
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
  std::cout << "Particle generated!" << std::endl;
}

Particle::~Particle() { std::cout << "Particle destructed!" << std::endl; }

const Vec3D &Particle::getX() const { return x; }

const Vec3D &Particle::getV() const { return v; }

const Vec3D &Particle::getF() const { return f; }

void Particle::setX(Vec3D &x_) { this->x = x_; }

void Particle::setV(Vec3D &v_) { this->v = v_; }

void Particle::setF(Vec3D &f_) { this->f = f_; }

void Particle::delayF() {
    this->old_f = this->f;
    this->f = Vec3D(0);
}

const Vec3D &Particle::getOldF() const { return old_f; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x.asArray() << " v: " << v.asArray() << " f: " << f.asArray() << " old_f: " << old_f.asArray() << " type: " << type;
  return stream.str();
}

bool Particle::operator==(Particle &other) {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
         (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, Particle &p) {
  stream << p.toString();
  return stream;
}
