# Build the project using CMake.
# https://github.com/marketplace/actions/cmake-action

name: CMake Build CI

on:
  pull_request:
    types: [synchronize]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          args: -DENABLE_VTK_OUTPUT=OFF
      - name: Run Tests
        uses: threeal/ctest-action@v1.1.0
