# Build the project using CMake.
# https://github.com/marketplace/actions/cmake-action

name: CMake Build CI

on:
  pull_request:
    types: [synchronize]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Restore CMake Cache
        uses: actions/cache/restore@v4
        with:
            path: |
                build/_deps
                build/CMakeFiles
                build/CMakeCache.txt
            key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeCache.txt') }}

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            CMAKE_POLICY_VERSION_MINIMUM=3.5
            -DENABLE_VTK_OUTPUT=OFF
          args: -DCMAKE_CXX_FLAGS="-fsanitize=address"

      - name: Save CMake Cache
        uses: actions/cache/save@v4
        with:
            path: |
                build/_deps
                build/CMakeFiles
                build/CMakeCache.txt
            key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeCache.txt') }}

      - name: Run Tests
        uses: threeal/ctest-action@v1.1.0
