# Code Documentation Deployment to GitHub Pages using Doxygen.
# 
# https://github.com/marketplace/actions/doxygen-github-pages-deploy-action

name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
          config_file: Doxyfile
