# Code Testing Build using Google Test Framework.
# https://github.com/marketplace/actions/setup-googletest

name: Google Test CI

on:
  workflow_run:
    # only run if cmake could build the project
    workflows: ["CMake Build CI"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: Bacondish2023/setup-googletest@v1.0.1
        with:
          tag: v1.14.0
